server:
  port: 8093

spring:
  application:
    name: flight-service

  datasource:
    url: jdbc:postgresql://localhost:5432/aero_architect_flights
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
