apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 8091         # ClusterIP port
      targetPort: 8091   # Container port
  type: ClusterIP
