apiVersion: v1
kind: Service
metadata:
  name: flight-service
  labels:
    app: flight-service
spec:
  selector:
    app: flight-service
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP
